server:
  port: 80
  servlet:
    context-path: /discipline
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/self_discipline?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5 #最小空闲连接数量
      maximum-pool-size: 20 #连接池最大连接数，默认是10
      auto-commit: true #控制从池中获取的连接的默认自动提交行为
      idle-timeout: 30000 #空闲连接存活的最大时间30秒
      max-lifetime: 60000 #池中连接的最长生命周期（为0表示永生）
      connection-timeout: 30000 #数据库连接超时时间（默认30秒）
      pool-name: infantaHikariCP #连接池名称
      connection-test-query: SELECT 1 FROM DUAL
    ################ Redis 基础配置 ##############
    # Redis数据库索引（默认为0）
  redis:
    database: 0
    host: 188.131.253.106
    port: 6379
    password: root
    timeout: 3000
    ################ Redis 线程池设置 ##############
    lettuce:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8    # 连接池中的最大空闲连接 默认 8
        min-idle: 0    # 连接池中的最小空闲连接 默认 0










